name: outfit-transformer
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - torch==2.2.0
    - torchvision==0.17.0
    - torchaudio==2.2.0
    - pillow==11.0.0
    - transformers==4.48.3
    - scikit-learn
    - faiss-cpu
    - wandb
    - tqdm
    - gradio
    - opencv-python